-- Criando um banco de dados
CREATE DATABASE IF NOT EXISTS SUCOS;

-- apagando o banco de dados
-- DROP DATABASE SUCOS;

CREATE TABLE IF NOT EXISTS PRODUTOS (
-- O valor padrão do auto_increment é 1
    PRODUTO INT UNSIGNED NOT NULL,
    -- AUTO_INCREMENT=100,
    NOME VARCHAR(50) NOT NULL,
    EMBALAGEM VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    SABOR VARCHAR(50) NULL,
    PRECO_TABELA DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    PRECO FLOAT(5,3) NOT NULL DEFAULT 0.000,
    ESTOQUE INT UNSIGNED NOT NULL DEFAULT 0,
    ENUM('NATURAL', 'INDUSTRIALIZADO') NOT NULL DEFAULT 'NATURAL',
    PRIMARY KEY (CODIGO),
);

-- apagando a tabela
-- DROP TABLE SUCOS;

-- Criando a tabela clientes
CREATE TABLE CLIENTES
(
    CPF VARCHAR (11) NOT NULL,
    NOME VARCHAR (100) ,
    ENDERECO1 VARCHAR (150) ,
    ENDERECO2 VARCHAR (150) ,
    BAIRRO VARCHAR (50) ,
    CIDADE VARCHAR (50) ,
    ESTADO VARCHAR (2) ,
    CEP VARCHAR (8) ,
    IDADE SMALLINT,
    SEXO VARCHAR (1) ,
    LIMITE_CREDITO FLOAT ,
    VOLUME_COMPRA FLOAT ,
    PRIMEIRA_COMPRA BIT ,
    PRIMARY KEY (CPF)
);

-- Criando a tabela Vendedores
CREATE TABLE VENDEDORES
(
    MATRICULA varchar(5), 
    NOME varchar(100), 
    PERCENTUAL_COMISSAO float
    PRIMARY KEY (MATRICULA)
);


-- Inserindo dados na tabela
INSERT INTO PRODUTO (
produto, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA, ESTOQUE) VALUES (
'1040107', 'Light - 350 ml - Melancia', 'Lata', '350 ml', 'Melancia', 4.56, 100);

INSERT INTO VENDEDORES (
    MATRICULA,
    NOME,
    PERCENTUAL_COMISSAO
)   
VALUES (
    '00233',
    'João Geraldo da Fonseca',
    0.05
);

-- Inserindo dados na tabela
INSERT INTO PRODUTO (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO produto (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO produto (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51);


-- Pesquisando todos os tbprodutos;
SELECT * FROM produto;


-- adicionando mais registros
INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
 ('00235','Márcio Almeida Silva',0.08);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES
('00236','Cláudia Morais',0.08);


INSERT INTO produto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO produto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

-- alterando registros
UPDATE tbproduto SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931';

UPDATE tbproduto SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

UPDATE TABELA_DE_VENDEDORES SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';

UPDATE TABELA_DE_VENDEDORES SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';

-- apagando registros
DELETE FROM tbproduto WHERE PRODUTO = '1078680';

-- trabalhando com data
USE sucos;
ALTER TABLE CLIENTES ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO Clientes (
CPF, 
NOME, 
ENDERECO1, 
ENDERECO2, 
BAIRRO, 
CIDADE, 
ESTADO, 
CEP, 
IDADE, 
SEXO, 
LIMITE_CREDITO, 
VOLUME_COMPRA, 
PRIMEIRA_COMPRA, 
DATA_NASCIMENTO) VALUES (
'00388934505', 
'João da Silva', 
'Rua projetada A número 10', 
'', 
'Vila Roman', 
'CARATINGA', 
'Amazonas', 
'2222222', 
30, 
'M', 
10000.00, 
2000, 
0, 
'1989-10-05');

-- ALTERANDO A TABELA DE VENDEDORES
DROP TABLE TABELA_DE_VENDEDORES;

CREATE TABLE TABELA_DE_VENDEDORES
( MATRICULA varchar(5),
NOME varchar(100),
PERCENTUAL_COMISSAO float,
DATA_ADMISSAO date,
DE_FERIAS bit);

ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00235','Márcio Almeida Silva','2014-08-15',0.08,0);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00236','Cláudia Morais','2013-09-17',0.08,1);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins','2017-03-18',0.11,1);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00238','Pericles Alves','2016-08-21',0.11,0);


-- SELECIONANDO REGISTROS
ELECT CPF, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA FROM CLIENTES;

-- FILTRANDO REGISTROS
SELECT * FROM PRODUTOS WHERE SABOR = 'Cítricos';

-- FILTRANDO COM "DIFERENTE DE"
SELECT * FROM CLIENTES WHERE NOME <> 'Fernando Cavalcante';


SELECT * FROM tbcliente WHERE DATA_NASCIMENTO > '1995-01-13';

-- FILTRO COMPOSTO
SELECT * FROM clienteS WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M')
 OR (cidade = 'Rio de Janeiro' OR BAIRRO = 'Jardins');

